package app.mishana.tv.audio

import android.content.Context
import android.media.AudioAttributes
import android.media.SoundPool
import android.os.Handler
import android.os.Looper
import app.mishana.tv.R
import app.mishana.tv.game.Cue
import app.mishana.tv.game.CuePlay
import app.mishana.tv.game.SoundSink
import java.util.concurrent.ConcurrentHashMap

/**
 * DESIGN §6.4 on the device: every cue (res/raw, generated by tools/gen-sounds) is loaded into one SoundPool at start;
 * a cue that has not finished loading is skipped, never queued (every sound has a visual counterpart).
 * Two buses: SFX and stingers ([Cue.Bus.gain]); the remote's UI ticks sit below both. Main thread only.
 */
class SoundPoolPlayer(context: Context) : SoundSink {
    private val pool: SoundPool = SoundPool.Builder()
        .setMaxStreams(MAX_STREAMS)
        .setAudioAttributes(
            AudioAttributes.Builder()
                .setUsage(AudioAttributes.USAGE_GAME)
                .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
                .build(),
        )
        .build()
    private val loaded = ConcurrentHashMap.newKeySet<Int>()
    private val ids: Map<Cue, Int>
    private val handler = Handler(Looper.getMainLooper())
    private val streams = ArrayDeque<Int>()

    init {
        pool.setOnLoadCompleteListener { _, sampleId, status -> if (status == 0) loaded += sampleId }
        val app = context.applicationContext
        ids = Cue.entries.associateWith { pool.load(app, rawRes(it), 1) }
    }

    override fun play(p: CuePlay) {
        val id = ids[p.cue] ?: return
        val run = Runnable {
            if (id !in loaded) return@Runnable
            val v = p.cue.bus.gain
            val priority = when (p.cue.bus) {
                Cue.Bus.STING -> 2
                Cue.Bus.SFX -> 1
                Cue.Bus.UI -> 0
            }
            val stream = pool.play(id, v, v, priority, 0, p.rate.coerceIn(0.5f, 2f))
            if (stream != 0) {
                streams.addLast(stream)
                while (streams.size > MAX_STREAMS * 2) streams.removeFirst()
            }
        }
        if (p.delayMs > 0) handler.postDelayed(run, p.delayMs) else run.run()
    }

    override fun stopAll() {
        handler.removeCallbacksAndMessages(null)
        for (s in streams) pool.stop(s)
        streams.clear()
    }

    override fun release() {
        stopAll()
        pool.release()
    }

    private companion object {
        const val MAX_STREAMS = 8

        fun rawRes(cue: Cue): Int = when (cue) {
            Cue.JOIN -> R.raw.sfx_join
            Cue.LEAVE -> R.raw.sfx_leave
            Cue.READY -> R.raw.sfx_ready
            Cue.ALL_READY -> R.raw.sfx_all_ready
            Cue.TURN -> R.raw.sfx_turn
            Cue.TICK -> R.raw.sfx_tick
            Cue.TICK_LAST -> R.raw.sfx_tick_last
            Cue.TIME_UP -> R.raw.sfx_time_up
            Cue.VOTE_CAST -> R.raw.sfx_vote_cast
            Cue.DRUMROLL -> R.raw.sfx_drumroll
            Cue.CHIP_LAND -> R.raw.sfx_chip_land
            Cue.STAMP -> R.raw.sfx_stamp
            Cue.FLIP -> R.raw.sfx_flip
            Cue.HEARTBEAT -> R.raw.sfx_heartbeat
            Cue.WHEEL -> R.raw.sfx_wheel
            Cue.ERROR -> R.raw.sfx_error
            Cue.STING_CIVILIAN -> R.raw.sting_civilian
            Cue.STING_MOLE -> R.raw.sting_mole
            Cue.STING_BLANK -> R.raw.sting_blank
            Cue.STING_CORRECT -> R.raw.sting_correct
            Cue.STING_WRONG -> R.raw.sting_wrong
            Cue.STING_WIN_CIVILIANS -> R.raw.sting_win_civilians
            Cue.STING_WIN_INFILTRATORS -> R.raw.sting_win_infiltrators
            Cue.UI_MOVE -> R.raw.ui_move
            Cue.UI_SELECT -> R.raw.ui_select
            Cue.UI_BACK -> R.raw.ui_back
        }
    }
}
