// Pure core of tools/gen-android-strings (SPEC §11.1, §11.3). No I/O here; see main.ts.

export type Locale = "en" | "fr" | "ar";
export type PluralCategory = "zero" | "one" | "two" | "few" | "many" | "other";
export type MessageValue = string | Partial<Record<PluralCategory, string>>;
export type MessageFile = Record<string, MessageValue>;
export type MessageSet = Record<Locale, MessageFile>;

export const LOCALES: readonly Locale[] = ["en", "fr", "ar"];
export const HEADER = "<!-- GENERATED by tools/gen-android-strings. Do not edit. -->";
// SPEC-GAP: §11.3 gives only the XML header; the Kotlin file uses the same text as a line comment.
export const KOTLIN_HEADER = "// GENERATED by tools/gen-android-strings. Do not edit.";

export const OUTPUT_PATHS: Record<Locale, string> = {
  en: "tv-app/app/src/main/res/values/strings_generated.xml",
  fr: "tv-app/app/src/main/res/values-fr/strings_generated.xml",
  ar: "tv-app/app/src/main/res/values-ar/strings_generated.xml",
};
export const KOTLIN_PATH = "tv-app/app/src/main/java/app/mishana/tv/i18n/I18nKeys.kt";

const KEY_RE = /^[a-z][a-zA-Z0-9]*(\.[a-z][a-zA-Z0-9]*)+$/;
const PLACEHOLDER_RE = /\{([a-z][a-zA-Z0-9]*)\}/g;
const ALL_CATEGORIES: readonly PluralCategory[] = ["zero", "one", "two", "few", "many", "other"];
// §11.1: EN one/other; FR one/other (many optional); AR all six.
const ALLOWED_CATEGORIES: Record<Locale, ReadonlySet<PluralCategory>> = {
  en: new Set(["one", "other"]),
  fr: new Set(["one", "many", "other"]),
  ar: new Set(ALL_CATEGORIES),
};

export class GenError extends Error {}

/** `phase.mrWhiteGuess` → `phase__mr_white_guess` (§11.3 rule 1). */
export function resourceName(key: string): string {
  return key
    .split(".")
    .map((seg) => seg.replace(/[A-Z]/g, (c) => `_${c}`).toLowerCase())
    .join("__");
}

/** Placeholder names in order of first appearance. */
export function placeholders(text: string): string[] {
  const out: string[] = [];
  for (const m of text.matchAll(PLACEHOLDER_RE)) {
    const name = m[1] as string;
    if (!out.includes(name)) out.push(name);
  }
  return out;
}

function isPlural(v: MessageValue): v is Partial<Record<PluralCategory, string>> {
  return typeof v === "object" && v !== null;
}

function forms(v: MessageValue): string[] {
  return isPlural(v) ? ALL_CATEGORIES.flatMap((c) => (v[c] === undefined ? [] : [v[c] as string])) : [v];
}

/** Argument order for a key: first appearance in the EN string (EN `other` for plurals), §11.3 rule 2. */
export function argOrder(enValue: MessageValue): string[] {
  if (!isPlural(enValue)) return placeholders(enValue);
  const order = placeholders(enValue.other ?? "");
  for (const f of forms(enValue)) for (const p of placeholders(f)) if (!order.includes(p)) order.push(p);
  return order;
}

/** Android string-resource escaping of a literal run (§11.3 rule 4). */
export function escapeLiteral(text: string): string {
  return text
    .replace(/\\/g, "\\\\")
    .replace(/'/g, "\\'")
    .replace(/"/g, '\\"')
    .replace(/\r?\n/g, "\\n")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

/** Converts one message form to Android resource text: escaping plus `{name}` → `%N$s` / `{count}` → `%N$d`. */
export function convert(text: string, order: readonly string[], where = "?"): string {
  if (text.includes("%")) throw new GenError(`${where}: a literal "%" is forbidden (§11.1)`);
  let out = "";
  let last = 0;
  for (const m of text.matchAll(PLACEHOLDER_RE)) {
    const name = m[1] as string;
    const literal = text.slice(last, m.index);
    out += escapeLiteral(literal);
    const n = order.indexOf(name);
    if (n < 0) throw new GenError(`${where}: placeholder {${name}} is not in the EN string`);
    out += `%${n + 1}$${name === "count" ? "d" : "s"}`;
    last = m.index + m[0].length;
  }
  out += escapeLiteral(text.slice(last));
  // Any brace left over is a malformed placeholder.
  if (/[{}]/.test(text.replace(PLACEHOLDER_RE, ""))) throw new GenError(`${where}: malformed placeholder in "${text}"`);
  if (out.startsWith("@") || out.startsWith("?")) out = `\\${out}`;
  return out;
}

function sameSet(a: readonly string[], b: readonly string[]): boolean {
  return a.length === b.length && a.every((x) => b.includes(x));
}

function union(v: MessageValue): string[] {
  const out: string[] = [];
  for (const f of forms(v)) for (const p of placeholders(f)) if (!out.includes(p)) out.push(p);
  return out.sort();
}

/** Validates the three files against §11.1. Returns every problem found (empty = valid). */
export function validate(set: MessageSet): string[] {
  const errors: string[] = [];
  const enKeys = Object.keys(set.en);
  for (const loc of LOCALES) {
    const file = set[loc];
    for (const key of Object.keys(file)) {
      if (!KEY_RE.test(key)) errors.push(`${loc}: invalid key "${key}"`);
      if (loc !== "en" && !(key in set.en)) errors.push(`${loc}: extra key "${key}" (not in en.json)`);
    }
    for (const key of enKeys) {
      const v = file[key];
      const en = set.en[key] as MessageValue;
      if (v === undefined) {
        errors.push(`${loc}: missing key "${key}"`);
        continue;
      }
      if (typeof v !== "string" && !isPlural(v)) {
        errors.push(`${loc}: "${key}" must be a string or a plural object`);
        continue;
      }
      for (const f of forms(v)) {
        if (typeof f !== "string") errors.push(`${loc}: "${key}" has a non-string plural form`);
        else if (f.includes("%")) errors.push(`${loc}: "${key}" contains a literal "%"`);
        else if (/[{}]/.test(f.replace(PLACEHOLDER_RE, ""))) errors.push(`${loc}: "${key}" has a malformed placeholder`);
      }
      if (isPlural(v) !== isPlural(en)) {
        errors.push(`${loc}: "${key}" must be ${isPlural(en) ? "a plural object" : "a plain string"} like en`);
        continue;
      }
      if (isPlural(v)) {
        for (const c of Object.keys(v)) {
          if (!ALLOWED_CATEGORIES[loc].has(c as PluralCategory)) errors.push(`${loc}: "${key}" has plural category "${c}" not allowed for ${loc}`);
        }
        if (v.other === undefined) errors.push(`${loc}: "${key}" plural is missing "other"`);
        if (!sameSet(union(v), union(en))) errors.push(`${loc}: "${key}" placeholders {${union(v).join(",")}} differ from en {${union(en).join(",")}}`);
      } else if (!sameSet(union(v), union(en))) {
        errors.push(`${loc}: "${key}" placeholders {${union(v).join(",")}} differ from en {${union(en).join(",")}}`);
      }
    }
  }
  // Resource-name collisions (rule 1), including the extra app_name (rule 6).
  const seen = new Map<string, string>([["app_name", "(app_name)"]]);
  for (const key of enKeys) {
    const name = resourceName(key);
    const prev = seen.get(name);
    if (prev !== undefined) errors.push(`resource name collision: "${key}" and "${prev}" both map to ${name}`);
    else seen.set(name, key);
  }
  if (!("brand.appName" in set.en)) errors.push(`en: missing key "brand.appName" (needed for app_name)`);
  return errors;
}

/** Builds strings_generated.xml for one locale. Assumes `validate` passed. */
export function buildXml(set: MessageSet, loc: Locale): string {
  const lines = ['<?xml version="1.0" encoding="utf-8"?>', HEADER, "<resources>"];
  const file = set[loc];
  const appName = file["brand.appName"];
  if (typeof appName === "string") lines.push(`    <string name="app_name">${convert(appName, [], `${loc}:brand.appName`)}</string>`);
  for (const key of Object.keys(set.en)) {
    const v = file[key] as MessageValue;
    const order = argOrder(set.en[key] as MessageValue);
    const name = resourceName(key);
    const where = `${loc}:${key}`;
    if (isPlural(v)) {
      lines.push(`    <plurals name="${name}">`);
      for (const c of ALL_CATEGORIES) {
        const f = v[c];
        if (f !== undefined) lines.push(`        <item quantity="${c}">${convert(f, order, `${where}.${c}`)}</item>`);
      }
      lines.push("    </plurals>");
    } else {
      lines.push(`    <string name="${name}">${convert(v, order, where)}</string>`);
    }
  }
  lines.push("</resources>", "");
  return lines.join("\n");
}

/** Builds I18nKeys.kt (§11.3 rule 5). */
export function buildKotlin(set: MessageSet): string {
  const strings: string[] = [];
  const plurals: string[] = [];
  for (const [key, v] of Object.entries(set.en)) {
    const entry = `        "${key}" to R.${isPlural(v) ? "plurals" : "string"}.${resourceName(key)},`;
    (isPlural(v) ? plurals : strings).push(entry);
  }
  return [
    KOTLIN_HEADER,
    "package app.mishana.tv.i18n",
    "",
    "import app.mishana.tv.R",
    "",
    "object I18nKeys {",
    "    val strings: Map<String, Int> = mapOf(",
    ...strings,
    "    )",
    "    val plurals: Map<String, Int> = mapOf(",
    ...plurals,
    "    )",
    "}",
    "",
  ].join("\n");
}

/** All outputs keyed by repo-relative path. Throws GenError when validation fails. */
export function generate(set: MessageSet): Map<string, string> {
  const errors = validate(set);
  if (errors.length > 0) throw new GenError(`i18n validation failed:\n  ${errors.join("\n  ")}`);
  const out = new Map<string, string>();
  for (const loc of LOCALES) out.set(OUTPUT_PATHS[loc], buildXml(set, loc));
  out.set(KOTLIN_PATH, buildKotlin(set));
  return out;
}
